# Generated by Django 5.0.1 on 2024-04-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_profile_old_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address2',
            new_name='province',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
