# Generated by Django 5.0.1 on 2024-04-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_shipped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_address2',
            new_name='shipping_province',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_state',
        ),
    ]
